CREATE DATABASE IF NOT EXISTS blog;
USE blog;

CREATE TABLE IF NOT EXISTS user (
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id INT AUTO_INCREMENT,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS post (
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    cover VARCHAR(255) NOT NULL,
    tags VARCHAR(255) NOT NULL,
    category INT NOT NULL,
    is_draft BOOLEAN DEFAULT true,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id INT AUTO_INCREMENT,
    PRIMARY KEY (id),
);
